language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install g++ openjdk-7-jdk python-dev python3-dev

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - python -m pytest tests

notifications:
  slack: maybestudio:Q9Nf77xsp5W70wr3LCxh2htJ
  email: false